apiVersion: apps/v1
kind: Deployment

metadata:
  name: gitops-demo
  namespace: gitops-demo
  labels:
    app: gitops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gitops-demo

  template:
    metadata:
      labels:
        app: gitops-demo

    spec:
      containers:
      - name: gitops-demo

        image: 759945100402.dkr.ecr.eu-north-1.amazonaws.com/gitops-demo:a57bda45ecc5464d4559b25e8ff6f3413c35caff

        imagePullPolicy: Always

        ports:
        - containerPort: 8081

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20